name: Add Issue to Repository Project
on:   
  workflow_call:
    inputs:
      project-url:
        type: string
        required: true
    secrets:
      github-token:
        required: true

jobs:
 add_to_project:
    name: Add Issue to Repository Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          #Enter the project's URL
          project-url: ${{ inputs.project-url }}
          #Add a repository secret in your repository settings and use it here
          github-token: ${{ secrets.github-token }}
          #Issues that have the specified label will be added to the project (Currently not working)
          #labeled: to-do
          #label-operator: OR