name: Add Labels to New Issues
on:
  issues:
    types:
     - opened

jobs:
  add-label-to-issue:
    name: Create Labels
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          #Add the label for the opened issue
          add-labels: "to-do"
  
  call-add-to-project:
    # {owner}/{repo}/.github/workflows/{filename}@{ref} for reusable workflows in public repositories.
    # ./.github/workflows/{filename} for reusable workflows in the same repository.
    uses: ./.github/workflows/add-issue-to-project.yml
