name: GitHub Actions For Issues
on:
  issues:
    types:
     - opened

jobs:
  create_label:
    name: Create Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-label'
          token: ${{ secrets.GITHUB_TOKEN }}
          label-name: 'to-do'
          label-color: '0095b3'
          label-desc: 'The issue needs to be assigned to members'
  
  add_label_to_issue:
      name: Set Labels
      runs-on: ubuntu-latest
      needs: create_label
      steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'set-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'to-do'
      
      - uses: actions/add-to-project@v0.3.0
        if: contains(github.event.issue.labels.*.name, 'to-do')
        with:
          project-url: https://github.com/users/lmlLanuza/projects/2
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
