name: GitHub Actions For Issues
on:
  issues:
    types:
     - opened

jobs:
  add_label_to_issue:
    name: Create Labels
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: "to-do"

  add_to_project:
    name: Add Issue to Project Board
    needs: add_label_to_issue
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: https://github.com/users/lmlLanuza/projects/2