name: GitHub Actions for Reassigning Issues in Projects
on:
  issues:
    types: 
     - labeled
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: lmlLanuza/sample-project
          column:  Status
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}