name: GitHub Actions for Reassigning Issues in Projects
on:
  issues:
    types: 
     - labeled
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: sample-project
          column: in-progress
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}