name: GitHub Actions for Reassigning Issues in Projects
on:
  issues:
    types: 
     - labeled
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
        with:
          action-token: "${{ secrets.Access_token }}"
          project-url: "https://github.com/lmlLanuza/test-workflows/projects/2"
          column-name: "New issues should show up here"