name: GitHub Actions for Reassigning Issues in Projects
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.MY_GITHUB_TOKEN }}"
        project-url: "https://github.com/users/lmlLanuza/projects/2"
        column-name: "in-progress"
        label-name: "in-progress"
        columns-to-ignore: "In Review,Ready to deploy,Done"