name: Add a new GitHub Project card linked to a GitHub issue to the specified project column
on:
  issues:
    types:
     - labeled
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/users/lmlLanuza/projects/2
        GITHUB_PROJECT_COLUMN_NAME: in-progress