name: Move issue to in-progress board
on:
  issues:
    types:
      - labeled

env: 
  GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  USER: lmlLanuza
  PROJECT_NUMBER: 2
  ISSUE_ID: PVTI_lAHOBGEuI84AHIcwzgDBagg   #${{ github.event.issue.node_id }}

jobs:
  track_issues:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get project node ID #Project ID: PVT_kwHOBGEuI84AHIcw
        run: |
          gh api graphql -f query='
            query($user: String!, $number: Int!){
              user(login: $user){
                projectV2(number: $number) {
                  id
                  fields(last:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f user=$USER -F number=$PROJECT_NUMBER > project_data.json

           echo 'PROJECT_ID='$(jq '.data.user.projectV2.id' project_data.json) >> $GITHUB_ENV
           echo 'STATUS_FIELD_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
      - name: Get field node ID   #Status ID: PVTSSF_lAHOBGEuI84AHIcwzgEHDpY | to-do option ID: f75ad846 |  #in-progress: 47fc9ee4
        run: | 
          gh api graphql -f query='
            query{
              node(id: "PVT_kwHOBGEuI84AHIcw") {
                ... on ProjectV2 {
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2IterationField {
                        id
                        name
                        configuration {
                          iterations {
                            startDate
                            id
                          }
                        }
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }'
      
      - name: Get item field ID  #Item ID: PVTI_lAHOBGEuI84AHIcwzgDAQNo
        run: |
          gh api graphql -f query='
            query{
              node(id: "PVT_kwHOBGEuI84AHIcw") {
                ... on ProjectV2 {
                  items(first: 20) {
                    nodes{
                      id
                      fieldValues(first: 8) {
                        nodes{                
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                                }
                              }
                            }
                          ... on ProjectV2ItemFieldDateValue {
                            date
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                          }              
                        }
                        content{              
                          ... on DraftIssue {
                            title
                            body
                          }
                          ... on Issue {
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                          ... on PullRequest {
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }'
      
      - name: Update status in Projects
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project
                  itemId: $issue
                  fieldId: $statusfield
                  value: { 
                    singleSelectOptionId: "47fc9ee4"
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID -f statusfield=$STATUS_FIELD_ID