on:
  issues:
    types:
      - labeled
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status
        uses: peter-evans/create-or-update-project-card@v2.0.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          project-number: 2
          column-name: in-progress
      - name: Check output
        run: echo ${{ steps.coupc.outputs.card-id }}